language: node_js
sudo: false
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


env:
  global:
    - GH_OWNER: zhaochunqi
    - GH_PROJECT_NAME: zhaochunqi.github.io
    
branches:
  only:
    - source
    
# Build Lifecycle

install:
  - npm install

script:
  - git clone -b master https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} public
  - hexo g
  - git config --global user.name "zhaochunqi"
  - git config --global user.email git@zhaochunqi.com
  - cd public
  - git add --all
  - git commit -m "$(curl -s http://whatthecommit.com/ | awk '/<p>/ {sub("<p>", ""); print }')"
  - git remote set-url --add --push origin https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME}
  - git remote set-url --add --push origin https://${coding_account}:${coding_passwd}@git.coding.net/harchiko/harchiko.git
  - git remote -v
  - git push -f origin master
