branches:
  only:
  - source

language: node_js

sudo: false

node_js:
- '0.12'

before_install:
- openssl aes-256-cbc -K $encrypted_13d35555abe0_key -iv $encrypted_13d35555abe0_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "zhaochunqi"
- git config --global user.email git@zhaochunqi.com
- git clone -b master git@github.com:zhaochunqi/zhaochunqi.github.io.git .deploy_git

install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-deployer-git --save

script:
- hexo clean
- hexo g
- hexo d