# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Weekly: /categories/weekly
  随想: /categories/microblog
  Archives: /archives/
  # Tags: /tags
  # Categories: /categories
  # About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: false
  fancybox: false

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: zcq.qiqi@gmail.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/zhaochunqi
  weibo: https://weibo.com/zhaocq
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: YECzMLE9UTvajIqEbA5NK8wN-gzGzoHsz
  app_key: vK6VPlmNULOlnr5q6CFvqozN

# Baidu Analytics
baidu_analytics: cfffa20d202ba9f4f0d6257e1cc94ea6
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics: UA-42448552-1
# Google Verification
google_verification:

# Disqus
disqus_shortname: blog-zhaochunqi

#Changyan
changyan:
  appid:
  appkey:

# ===========================================
# Version
# ===========================================
version: 2.6.0
