<div class="popup">
	<span class="search-icon fa fa-search"></span>
    <div class="algolia-search-input" id="algolia-search-input">
	    <input type="text" autocapitalize="off" autocomplete="off" autocorrect="off" role="textbox" spellcheck="false" id="local-search-input" placeholder="请输入搜索关键字..." class="form-control ais-search-box--input/>
    </div>
 <div id="local-search-result"></div>
 <span class="popup-btn-close">close</span>
</div>