menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/121189047
    GitHub: https://github.com/zhaochunqi
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: blog-zhaochunqi
duoshuo: 

# Analytics
# google-analytics:
ga: UA-42448552-1
# baidu-analytics:
ba: cfffa20d202ba9f4f0d6257e1cc94ea6

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
